### ISSUE TITLE
Functions for em/rem calculation

### ISSUE THREAD

**Issue by donny-dont** [AdalbertoLacruz/less_dart#10]
I've been using rem/em to scale up and down a site based on the display. I'm wondering if we could add functions to do the math there.

```
String rem(int fontSizeInPixels, [int baseFontSizeInPixels = 16]) =>
    '${fontSizeInPixels / baseFontSizeInPixels}rem';
```

**Comment by AdalbertoLacruz** [comment]
Could you send me a test example?

**Comment by donny-dont** [comment]
```
h2 {
  font-size: rem(32); // Should end up being `font-size: 2rem;`
}

header {
  padding: rem(20) 0; // Should end up being `padding: 1.25rem 0;`
}
```

Here's an example in SASS for REM http://www.stubbornella.org/content/2013/07/01/easy-peasy-rem-conversion-with-sass/.

**Comment by AdalbertoLacruz** [comment]
Could you test the new version?

See test examples in `test\less\extendedTest\function-rem.less` => `test\css\extendedTest\function-rem.css`

**Comment by donny-dont** [comment]
Worked perfectly. Thank you @AdalbertoLacruz!

**Comment by donny-dont** [comment]
Could you push this to pub? Then good to close.

Thanks again!

**Comment by AdalbertoLacruz** [comment]
Uploaded to pub.
