### ISSUE TITLE
Less ignores the relative urls flag

### ISSUE THREAD

**Issue by gchumillas** [AdalbertoLacruz/less_dart#12]
I tried to use the "relative paths" flag with no luck. The transformer ignores that directive. For example, the following file is in the same directory that the common.less file:

``` less
@import 'common.less';

/* more things */
```

Here's my pubspec.yaml transformer:

``` yaml
transformers:
- less_dart:
    other_flags:
      - --relative-urls
```

After running the dart server (pub serve), it prints something like this:

``` text
[Info from less-dart] ERROR lessc --no-color --relative-urls lib/components/axis_login.less > lib/components/axis_login.css took 0.0s
**** ERROR ****  see build/lib/components/axis_login.css

FileError: 'axis_app.less' wasn't found. Tried - axis_app.less in - on line 1, column 1:
1 @import 'axis_app.less';
..^
```

But if I execute the above command manually, it works well:

``` bash
# works like a charm
> lessc --no-color --relative-urls lib/components/axis_login.less > lib/components/axis_login.css took
```

**More info**
less: 0.3.3
OS: Xubuntu 16.04
Dart VM version: 1.16.0 (Tue Apr 26 14:18:21 2016) on "linux_x64"
Pub version: 1.16.0
lessc version: 2.7.1 (Less Compiler) [JavaScript]

**Comment by AdalbertoLacruz** [comment]
Could you send me file contents to start a test environment?

**Comment by gchumillas** [comment]
No problem. Attached is the project.
[app.zip](https://github.com/AdalbertoLacruz/less_dart/files/309309/app.zip)

If you take a look at the pubspec.yaml file, I replaced "--relative-paths" by "--rootpath" and "--include". In any case, it doesn't solve the problem. Relative paths are still being ignored.

Thanks.

**Comment by gchumillas** [comment]
To test the application, remove the "rootpath" and "include" flags from pubspec.yaml and replace them by the "relative-paths" flag.

**Comment by AdalbertoLacruz** [comment]
I don't understand very well the problem. Your description and the file contents don't match.

I guess the problem isn't the relative-urls, but the current directory used by the dart transformer (the project root).

Attached is a simplified working test 
[darttest.zip](https://github.com/AdalbertoLacruz/less_dart/files/310845/darttest.zip) with web/index.less as if it were at root level.

Please modify the test to show the problem.

**Comment by gchumillas** [comment]
Thanks so much for your time. So I misunderstood the use of the "relative-urls" flag. I changed the application and now it works as expected, but I also realized that I prefer to use the "rootpath" and the "include-path" flags :)

**Comment by gchumillas** [comment]
Looking on this issue. I created a very simple angular2 project from scratch:

``` bash
> stagehand web-angular
```

and I added the following less files:
- lib/common.less
- lib/app_component.less

The app_component.css file is loaded from app_component.dart:

``` dart
@Component(
    selector: 'my-app',
    templateUrl: 'app_component.html',
    styleUrls: const ['app_component.css'])
```

And, at the same time, app_component.less imports common.less, which is in the same directory. Then I excuted the `pub serve` command and it throws the following error:

``` text
[Info from less-dart] ERROR lessc --no-color --relative-urls lib/app_component.less > lib/app_component.css took 0.1s
**** ERROR ****  see build/lib/app_component.css

FileError: 'common.less' wasn't found. Tried - common.less in - on line 2, column 1:
1 //@import 'packages/test/common.less';
2 @import 'common.less';
..^
3

[Info from less-dart] lessc --no-color --relative-urls lib/common.less > lib/common.css took 0.0s
[Info from less-dart] ERROR lessc --no-color --relative-urls lib/app_component.less > lib/app_component.css took 0.0s
**** ERROR ****  see build/lib/app_component.css

FileError: 'common.less' wasn't found. Tried - common.less in - on line 2, column 1:
1 //@import 'packages/test/common.less';
2 @import 'common.less';
..^
3

Build error:
Transform StylesheetCompiler on test|lib/app_component.css threw error: Url test|lib/app_component.css.dart is not a valid asset: url
3

Build error:
Transform StylesheetCompiler on test|lib/app_component.css threw error: Url test|lib/app_component.css.dart is not a valid asset: url
```

Now copy and paste the above command and execute it directly from the project root:

``` bash
# change the the project root and execute the following command
> lessc --no-color --relative-urls lib/app_component.less > lib/app_component.css
```

It throws no errors.
May be it is a problem with Angular 2 and less_dart.

Attached is the test project.
[test.zip](https://github.com/AdalbertoLacruz/less_dart/files/310902/test.zip)
