### ISSUE TITLE
Unit tests are broken

### ISSUE THREAD

**Issue by zolotyh** [AdalbertoLacruz/less_dart#16]
When I run `pub run test` then I have this output

```
...
00:03 +211 -4: test/batch_test.dart:                                                                                               
```
4 tests has failed.

My dartvm version is 1.24.3 (Dart VM version: 1.24.3 (Wed Dec 13 23:26:59 2017) on "macos_x64")

**Comment by AdalbertoLacruz** [comment]
Changes are in 2.0.0
