### ISSUE TITLE
refreshStyles() support

### ISSUE THREAD

**Issue by dvorapa** [AdalbertoLacruz/less_dart#20]
Basically I want to make this:
```
StyleElement style = StyleElement()
    ..type = 'text/less'
    ..text = 'my new less code';
document.querySelector("head").insertAdjacentElement("beforeEnd", style);
less.refreshStyles();
```
But I wasn't able to do this using dart_less

**Comment by AdalbertoLacruz** [comment]
See the readme. The builder can process html files.

Any case, by programming see an example in the test:

https://github.com/AdalbertoLacruz/less_dart/blob/master/test/builder_test.dart
in Html Builder Test (3rd)

**Comment by dvorapa** [comment]
I don't understand. When a visitor on my website clicks on a button, I want to add less code to a page and preprocess it. Your example seems to add less code at build time, not after build time.

**Comment by AdalbertoLacruz** [comment]
I don't know about your specific use case.

Here is an minimal less -> css transformation by code:

https://github.com/AdalbertoLacruz/less_dart/blob/master/test/simply_test.dart

In the arguments list, you could replace 'test/less/css.less' by '-'
and supply the source with less.stdio.write(source)

See
https://github.com/AdalbertoLacruz/less_dart/blob/master/test/batch_test.dart
in lines 558-559.

**Comment by dvorapa** [comment]
Does the visitor of my web app need to have less installed? Because that would not be convenient. Or is lass_dart packaged with less?

**Comment by dvorapa** [comment]
Ahh, finally moved to stylus as less recounts some calc() to rem, which is always broken in my case
