### ISSUE TITLE
Relative imports don't support rebuild while serving

### ISSUE THREAD

**Issue by missvalentinep** [AdalbertoLacruz/less_dart#26]
_less_dart version: 2.3.5_
### Issue:
When we import `.less` file using its relative path, the changes in it are not applied after rebuild while serving. 

### Project setup to reproduce the issue:
There are two `.less` files. The first file imports the second one using its relative path, for example, `@import "./imported_style.less";`

### Steps to reproduce the issue:
1. Run `webdev serve`.
2. Make changes in `imported_style.less`.
3. Save, wait for rebuild to finish.
4. Refresh browser page - changes were not applied.

### Discovered workaround (in case it helps to narrow down the problem)
1. Importing `.less` file by its absolute path, for example `@import "packages/package_name/imported_style.less";`.
2. Changing something in the importing file, after making changes to the imported file.

In both of these cases the changes to the imported file become visible after rebuild and page refresh.

**Comment by AdalbertoLacruz** [comment]
Try 2.3.6
In some cases (Angular, ...) involving packages, the builder receives absolute paths, that must be converted to package notation to mark dependencies.
I hope this patch will resolve the issue.

**Comment by missvalentinep** [comment]
Yes, thank you!
