### ISSUE TITLE
feature request: support of less-plugin-autoprefix

### ISSUE THREAD

**Issue by missvalentinep** [AdalbertoLacruz/less_dart#27]
What is your opinion on adding support of less-plugin-autoprefix (https://github.com/less/less-plugin-autoprefix)? I believe a lot of people will find the ability to use this plugin extremely helpful.

If you don't mind, I can try to implement it myself and open a pull request afterwards.

**Comment by AdalbertoLacruz** [comment]
less-plugin-autoprefix requires autoprefixer and postcss. That would be > 200 files including code and test files to convert. Could be done, but is a big effort.

Less cool but simpler is to use mixins and variable interpolation:

https://stackoverflow.com/questions/18558368/is-there-a-generic-way-to-add-vendor-prefixes-in-less/18558614

https://github.com/less/less.js/issues/1199#issuecomment-18641212

I suggest the variable interpolation path.

**Comment by missvalentinep** [comment]
Thank you
