### ISSUE TITLE
less-plugin-clean-css attribute quotes

### ISSUE THREAD

**Issue by DmitriyLazarev** [AdalbertoLacruz/less_dart#29]
I use AngularDartWebApp with less_dart and less-plugin-clean-css plugin.
When I try to use

```
<div
    data-id="1"
    class="div">
    hello world
</div>

.div[data-id="1"] {
  color: red;
}
```
It becomes
```
<div
    data-id="1"
    class="div">
    hello world
</div>

.div[data-id=1] {
  color: red;
}
```
It breaks my build and styles, because of removed quotes in the selector. Can I somehow disable this rule for my project?

**Comment by AdalbertoLacruz** [comment]
clean-css removes quotes in the selector.

Now, in 2.3.8 (pub available), when a selector starts with number, the quotes are not removed.

**Comment by DmitriyLazarev** [comment]
@AdalbertoLacruz it works! Thank you!
