### ISSUE TITLE
Wildcards for entry_point

### ISSUE THREAD

**Issue by pcornelissen** [AdalbertoLacruz/less_dart#5]
Thanks for the great transformer!

I want to use it in a polymer dart based application, so I have a bunch (like 20+) polymer components and they share only a little bit of common css. So I end up with a lot of entry points and I have the chance to forget to add it to the entry points when I create the next component.

Is it possible that the transformer scans the project and converts less files automatically?
To prevent it from transforming the shared files that are only imported, there needs to be some kind of pattern matching, I guess.

maybe something like:

```
- less_dart:
     entry_points:
         - web/**.less
         - lib/**/less/*.less
```

This is using the ant syntax in which *\* matches files in subdirectories as well. Do you think something like that is possible?

Keep up the good work!

**Comment by AdalbertoLacruz** [comment]
Could you try the new transformer before release to pub. As the Readme says, it support default values for .less and .html files, and \* in the entry_points, and ! as exclusion path.

**Comment by pcornelissen** [comment]
Thank you, I'll try to have a look as soon as I have some time

**Comment by stevenroose** [comment]
So this works now?

**Comment by pcornelissen** [comment]
Oh sorry, yes this works!
