### ISSUE TITLE
working directory is always project root - should be relative to current file?

### ISSUE THREAD

**Issue by pcornelissen** [AdalbertoLacruz/less_dart#6]
I'm currently porting my static css to less using your plugin for the generation and one thing seems to be a little bit off/unusual.

I have a file 

```
$projectroot/less/common.less
```

Which is referenced by another file in $projectroot/web/ for example.
But I have to construct the @import path relative to $projectroot. This conflicts with other less tools and the way intellij tries to find related files for it's code completion. They expect paths that are relative to the file.

So currently I have to use:

```
@import "less/common";
```

Desirably is something like this:

```
@import "../less/common";
```

This would be a breaking change for existing less files, so there should presumably be a transformer setting whether the working directory is the project base or the file directory.

Sorry for creating all those issues :-)

**Comment by pcornelissen** [comment]
Sorry, must had a type before. somehow it works with relative paths now. Don't know what I did wrong before :-)

**Comment by AdalbertoLacruz** [comment]
In addition to relative paths you could use variables in the filename to
import.

See the import test for things such as:

@my_theme: "test";

@import "import/import-@{my_theme}-e.less";

2015-03-08 10:34 GMT+01:00 Patrick Cornelißen notifications@github.com:
