### ISSUE TITLE
Parse error for Polymer @apply

### ISSUE THREAD

**Issue by donny-dont** [AdalbertoLacruz/less_dart#9]
Currently the parser fails if you attempt to use the Polymer 1.0 mixins. See https://www.polymer-project.org/1.0/docs/devguide/styling.html.

Attempting to use it results in

``` shell
ParseError: directive options not recognised in - on line 18, column 15:
      17
      18         @apply(--scrollable-group-wrapper);
      .................^
      19
```

**Comment by donny-dont** [comment]
The hacks in https://github.com/less/less.js/issues/2715 seem to work but makes things quite ugly.

**Comment by AdalbertoLacruz** [comment]
Sorry, as far as know @apply yet isn't supported in lessc js.

**Comment by donny-dont** [comment]
Sure but can less_dart support it?

**Comment by AdalbertoLacruz** [comment]
Polymer defines mixins as:
  --mixin-name: { rules }
and use them with:
  @apply(--mixin-name);

Possibly could implement a pass-throw for @apply in the lessc directive system. But the mixin definition is more complex to parse and must be in a css file, external to lessc.

Could this be a solution for you?

**Comment by donny-dont** [comment]
I think I could live with that. Would be great if it could parse inside the mixin for stuff like px to em's but not sure how hard that would be.

**Comment by donny-dont** [comment]
Just wanted to note that it was super easy to get less_dart up and running. Really great stuff you have here. The polymer stuff is all new so I expect some hiccups but everything looks good.

**Comment by AdalbertoLacruz** [comment]
Could you try the new version?
For reference see the test:  test/less/extendedTest/apply.less
that result in: test/css/extendedText/apply.css

**Comment by donny-dont** [comment]
:shipit: worked great! Thanks @AdalbertoLacruz.

**Comment by AdalbertoLacruz** [comment]
I'm glad to hear that. It´s time to upgrade pub.
